# -------------- project specific parameters to be changed -------------- #

samples:
  prawn1:
    - 18-2595-01-Prawn1_S6_L001_R1_001.fastq.gz
    - 18-2595-01-Prawn1_S6_L001_R2_001.fastq.gz

# pipeline options
# FULL = all assembly and annotation options
# SD = spades assembly followed by diamond annotation
# SDN = spades assembly followed by diamond and blastn annotation
# TD = trinity assembly followed by diamond annotation
# HSDN = host removal, spades assembly followed by diamond and blastn annotation

pipeline: [full]

# single end (SE) or paired end (PE) reads?

endedness: PE

# -------------- pipeline parameters -------------- #

# Trimmomatic is used for trimming the sequencing reads
# The program requires an adapter file specific for the sequencing run
# and a minimum quality score can be given

trimmomatic_adapters: "config/TruSeq3-PE-2.fa"
trimmomatic_quality: 20
trimmomatic_minlen: 5


# Assembly parameters

draw_bandage: "True"

# location of reference databases

blast_nt: "/data/bioref/blast/ncbi/nt"
blast_nr: "/data/bioref/blast/ncbi/nr"
diamond_nr: "/data/bioref/diamond_db/nr"

silva_LSU_db: "/data/nea040/db/silva_rRNA_db/SILVA_132_LSUParc_tax_silva.DNA.fasta"
silva_SSU_db: "/data/nea040/db/silva_rRNA_db/SILVA_132_SSUParc_tax_silva.DNA.fasta"


# -------------- pipline data structure -------------- #

# could think about using accessing this directory structure through dicts
# this would all the user to change folder names easily
# however, the input parts of rules would have to be significantly more complicated

program_dir: "/flush3/nea040/mappd_master/mappd/"

sub_dirs:
  trim_dir: "01_trimmomatic"
  depletion_dir: "02_depletion"
  assembly_dir: "03_assembly"
  annot_dir: "04_annotation"