# -------------- project specific parameters to be changed -------------- #

# NOTE: can't include underscore in the sample name
# I split by this somewhere
# Perhaps I should include a little function to fix sample names in case
# also should make sure sample is a string to avoid R interpreting it as an int

samples:
  prawn1:
    - 18-2595-01-Prawn1_S6_L001_R1_001.fastq.gz
    - 18-2595-01-Prawn1_S6_L001_R2_001.fastq.gz
  prawn2:
    - 18-2595-02-Prawn2_S7_L001_R1_001.fastq.gz
    - 18-2595-02-Prawn2_S7_L001_R2_001.fastq.gz
  prawn3:
    - 18-2595-03-Prawn3_S8_L001_R1_001.fastq.gz
    - 18-2595-03-Prawn3_S8_L001_R2_001.fastq.gz


# pipeline options
# FULL = all assembly and annotation options
# SD = spades assembly followed by diamond annotation
# SDN = spades assembly followed by diamond and blastn annotation
# TD = trinity assembly followed by diamond annotation
# HSDN = host removal, spades assembly followed by diamond and blastn annotation

pipeline: [full]

# single end (SE) or paired end (PE) reads?

endedness: PE

# -------------- pipeline parameters -------------- #

## Trimming parameters ##
# Trimmomatic is used for trimming the sequencing reads
# The program requires an adapter file specific for the sequencing run
# and a minimum quality score can be given

trimmomatic_adapters: "config/TruSeq3-PE-2.fa"
trimmomatic_quality: 20
trimmomatic_minlen: 5

## Assembly parameters ##

draw_bandage: "True"

## Host depletion parameters ##

perform_host_depletion: "True"

# Can't download more than 10 hosts because this relies
# on the top 10 summary file. Even if more than 10 is given
# below, only 10 will be downloaded.
hosts_to_download: 1

# location of reference databases

blast_nt: "/data/bioref/blast/ncbi/nt"
blast_nr: "/data/bioref/blast/ncbi/nr"
diamond_nr: "/data/bioref/diamond_db/nr"

silva_LSU_db: "/data/nea040/db/silva_rRNA_db/SILVA_132_LSUParc_tax_silva.DNA.fasta"
silva_SSU_db: "/data/nea040/db/silva_rRNA_db/SILVA_132_SSUParc_tax_silva.DNA.fasta"
acc_to_taxids: "/data/nea040/db/ncbi_conversions/nucl_gb.accession2taxid"

nt_to_taxids: "/datasets/work/AAHL_PDNGS_WORK/db/ncbi_conversions/nt.acc2taxid.txt"


# -------------- pipline data structure -------------- #

# this allows the user to change folder names easily
# include the final forward slash in dir name

program_dir: "/datasets/work/AAHL_PDNGS_WORK/mappd/"

sub_dirs:
  trim_dir: "01_trimmomatic"
  depletion_dir: "02_depletion"
  assembly_dir: "03_assembly"
  annot_dir: "04_annotation"
