# -------------- project specific parameters to be changed -------------- #

# NOTE: can't include underscore in the sample name
# I split by this somewhere
# Perhaps I should include a little function to fix sample names in case
# also should make sure sample is a string to avoid R interpreting it as an int

samples:
#    Lung10:
#      - Lung10_1.2m.fastq
#      - Lung10_2.2m.fastq
#  prawn1:
#    - 18-2595-01-Prawn1_S6_L001_R1_001.fastq.gz
#    - 18-2595-01-Prawn1_S6_L001_R2_001.fastq.gz
#  prawn2:
#    - 18-2595-02-Prawn2_S7_L001_R1_001.fastq.gz
#    - 18-2595-02-Prawn2_S7_L001_R2_001.fastq.gz
#  prawn3:
#    - 18-2595-03-Prawn3_S8_L001_R1_001.fastq.gz
#    - 18-2595-03-Prawn3_S8_L001_R2_001.fastq.gz
    1201BrainLiver:
        - 18-1201-MagpieBrainLiverP_S3_L001_R1_001.fastq
        - 18-1201-MagpieBrainLiverP_S3_L001_R2_001.fastq
#    1202Brain:
#        - 18-1202-MagpieBrainP_S5_L001_R1_001.fastq
#        - 18-1202-MagpieBrainP_S5_L001_R2_001.fastq
#    1202Liver:
#        - 18-1202-MagpieLiverP_S4_L001_R1_001.fastq
#        - 18-1202-MagpieLiverP_S4_L001_R2_001.fastq
#    1203Brain:
#        - 18-1203-MagpieBrainP_S6_L001_R1_001.fastq
#        - 18-1203-MagpieBrainP_S6_L001_R2_001.fastq
#    1203Liver:
#        - 18-1203-MagpieLiver_S7_L001_R1_001.fastq
#        - 18-1203-MagpieLiver_S7_L001_R2_001.fastq

# pipeline options
# FULL = all assembly and annotation options
# SD = spades assembly followed by diamond annotation
# SDN = spades assembly followed by diamond and blastn annotation
# TD = trinity assembly followed by diamond annotation
# HSDN = host removal, spades assembly followed by diamond and blastn annotation

pipeline: [full]

# single end (SE) or paired end (PE) reads?

endedness: PE

# -------------- pipeline parameters -------------- #

## Trimming parameters ##
# Trimmomatic is used for trimming the sequencing reads
# The program requires an adapter file specific for the sequencing run
# and a minimum quality score can be given

trimmomatic_adapters: "config/TruSeq3-PE-2.fa"
trimmomatic_quality: 20
trimmomatic_minlen: 5

## Assembly parameters ##

draw_bandage: "True"

## Host depletion parameters ##

perform_host_depletion: "True"

# Can't download more than 10 hosts because this relies
# on the top 10 summary file. Even if more than 10 is given
# below, only 10 will be downloaded.
hosts_to_download: 1

## Annotation parameters ##

diamond_nr_evalue: 0.00001
# contigs smaller than this will be removed from further analysis
min_contig_size: 500

# location of reference databases

blast_nt: "/OSM/CDC/BIOINFO_CORE/reference/bioref/blast/ncbi/nt"
blast_nr: "/OSM/CDC/BIOINFO_CORE/reference/bioref/blast/ncbi/nr"
# note: had to use this specific database for latest diamond version
diamond_nr: "/OSM/CDC/BIOINFO_CORE/reference/bioref/diamond_db/nr_190301_v0924"

silva_LSU_db: "/datasets/work/AAHL_PDNGS_WORK/db/silva_rRNA_db/SILVA_132_LSUParc_tax_silva.DNA.fasta"
silva_SSU_db: "/datasets/work/AAHL_PDNGS_WORK/db/silva_rRNA_db/SILVA_132_SSUParc_tax_silva.DNA.fasta"

acc_to_taxids: "/datasets/work/AAHL_PDNGS_WORK/db/ncbi_conversions/nucl_gb.accession2taxid"
nt_to_taxids: "/datasets/work/AAHL_PDNGS_WORK/db/ncbi_conversions/nt.acc2taxid.txt"


# -------------- pipline data structure -------------- #

# this allows the user to change folder names easily
# include the final forward slash in dir name

program_dir: "/datasets/work/AAHL_PDNGS_WORK/mappd/"

sub_dirs:
  trim_dir: "01_trimmomatic"
  depletion_dir: "02_depletion"
  assembly_dir: "03_assembly"
  annotation_dir: "04_annotation"
