# -------------- project specific parameters to be changed -------------- #

samples:
  - "data/simulated_sample.1m"
  - "data/simulated_sample.l1m"



# -------------- pipeline parameters -------------- #

# Trimmomatic is used for trimming the sequencing reads
# The program requires an adapter file specific for the sequencing run
# and a minimum quality score can be given

trimmomatic_adapters: "data/TruSeq3-PE-2.fa"
trimmomatic_quality: 20
