## -------------- project specific parameters to be changed -------------- ##

# NOTE: can't include underscore in the sample name
# I split by this somewhere
# Perhaps I should include a little function to fix sample names in case
# also should make sure sample is a string to avoid R interpreting it as an int

samples:
  MS2008-01-1002:
    - ../1.raw/MS2008-01-1002-H7N7_S2_L001_R1_001.fastq.gz
    - ../1.raw/MS2008-01-1002-H7N7_S2_L001_R2_001.fastq.gz
  MS2008-15-0502:
    - ../1.raw/MS2008-15-0502-H5N2_S1_L001_R1_001.fastq.gz
    - ../1.raw/MS2008-15-0502-H5N2_S1_L001_R2_001.fastq.gz
  MS2008-28-1706:
    - ../1.raw/MS2008-28-1706-H7N6_S3_L001_R1_001.fastq.gz
    - ../1.raw/MS2008-28-1706-H7N6_S3_L001_R2_001.fastq.gz



## -------------- pipeline parameters -------------- ##

# type of sequences (RNA or DNA)
# this will change the assembler parameters
seq_type: "RNA"

# single end (SE) or paired end (PE) reads?
endedness: "PE"

# -------------- Trimming -------------- #

# Trimmomatic is used for trimming the sequencing reads
# The program requires an adapter file specific for the sequencing run
# and a minimum quality score can be given

trimmomatic_adapters: "config/NexteraPE-PE.fa"
trimmomatic_quality: 20
trimmomatic_minlen: 50

nanofilt_quality: 10

phix_genome: "config/phix174_ill.ref.fa"

# -------------- rRNA depletion -------------- #

# probably want to leave this on almost all the time
# maybe for DNA-Seq would save time by turning it off
# CANT TURN THIS OFF AT THE MOMENT
# WOULD NEED TO MODIFY THE OVERALL_ABUNDANCE PLOTS
rRNA_depletion: True
# set this at 1G lower than total
bbmap_max_memory: "-Xmx15g"

# -------------- host depletion -------------- #

# turn this off for cell-cultures / isolates
host_depletion: False

# Can't download more than 10 hosts because this relies
# on the top 10 summary file. Even if more than 10 is given
# below, only 10 will be downloaded.
hosts_to_download: 1

# -------------- Assembly -------------- #

# options for assembler include trinity, spades or megahit
# if RNA-Seq and SPAdes is chosen spades --rna mode will run
assembler: "trinity"
spades_max_memory: 16
trinity_max_memory: "16G"

# -------------- Annotation -------------- #

diamond_nr_evalue: 0.00001
# the minimum amount (%) that the query seq needs to aligned to be annotated
# turn this off for the moment - removes too many true viral hits
diamond_qcov: 0
# contigs smaller than this will be removed from further analysis
min_contig_size: 200
# take unannotated reads and do a diamond blastx on the reads
# may significantly increase the time required
analyse_unmapped: False

## -------------- Location of databases -------------- ##


blast_nt: "/datasets/work/bioinfo-core/reference/bioref/blast/ncbi/nt"
blast_nr: "/datasets/work/bioinfo-core/reference/bioref/blast/ncbi/nr"
# note: using the 'latest' shortcut - would need to check folder for actual db version
diamond_nr: "/datasets/work/bioinfo-core/reference/bioref/diamond_db_archive/nr_190301_v0924"

silva_LSU_db: "/datasets/work/aahl-pdngs/work/db/silva_rRNA_db/LSU/SILVA_132_LSUParc_tax_silva.DNA.fasta"
silva_SSU_db: "/datasets/work/aahl-pdngs/work/db/silva_rRNA_db/SSU/SILVA_132_SSUParc_tax_silva.DNA.fasta"

acc_to_taxids: "/datasets/work/aahl-pdngs/work/db/ncbi_conversions/nucl_gb.accession2taxid"
nt_to_taxids: "/datasets/work/aahl-pdngs/work/db/ncbi_conversions/nt.acc2taxid.txt"
gb_wgs_taxids: "/datasets/work/aahl-pdngs/work/db/ncbi_conversions/nucl_gb_wgs.accession2taxid"

# location of ART installation (only required for validation module)
art: "/datasets/work/aahl-pdngs/work/software/CAMISIM/tools/art_illumina-2.3.6"


## -------------- Pipline data structure -------------- ##

# this allows the user to change folder names easily
# include the final forward slash in dir name

program_dir: "/datasets/work/aahl-pdngs/work/mappd/"

sub_dirs:
  trim_dir: "01_trimmomatic"
  depletion_dir: "02_depletion"
  assembly_dir: "03_assembly"
  annotation_dir: "04_annotation"
