# -------------- project specific parameters to be changed -------------- #

samples:
  sim1: "data/sim1.fastq"
  sim2: "data/sim2.fastq"



# -------------- pipeline parameters -------------- #

# Trimmomatic is used for trimming the sequencing reads
# The program requires an adapter file specific for the sequencing run
# and a minimum quality score can be given

trimmomatic_adapters: "data/TruSeq3-PE-2.fa"
trimmomatic_quality: 20
trimmomatic_minlen: 50

# how many reads to subsample and use for assembly

subsampled_nReads: 100000
