name: mappd
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - megahit>=1
  - bbmap>=38.58
  - biopython>=1.74
  - blast>=2.9.0
  - bowtie2>=2.3.5
  - cairo>=1.14
  - diamond>=2.1
  - entrez-direct>=11.0
  - ete3>=3.1
  - fontconfig>=2.13
  - freetype>=2.9
  - pip>=19.1
  - prettytable>=0.7
  - python>=3.7
  - python-dateutil>=2.8
  - qt>=5.9.7
  - r>=3.6
  - r-dbplyr>=1.4.0
  - r-dplyr>=0.8
  - r-ggplot2>=3.1.1
  - r-knitr>=1.22
  - r-lubridate>=1.7
  - r-markdown>=0.9
  - r-prettyunits>=1
  - r-rcolorbrewer>=1
  - r-rmarkdown>=1.1
  - r-scales>=1.0.0
  - r-kableextra>=1.0
  - r-optparse>=1.0
  - r-tibble>=2.1
  - r-tidyr>=0.8
  - r-tidyverse>=1.2
  - r-plotly>=4.0
  - samtools>=1.8
  - scipy>=1.3
  - snakemake>=5.5
  - snakemake-minimal>=5.5
  - spades>=3.13
  - trimmomatic>=0.39
  - trinity>=2.11
  - urllib3>=1.24
  - yaml>=0.1
