channels:
  - defaults
  - conda-forge
  - bioconda
  
dependencies:
# general
  - snakemake>=5.2.1
  - python>=3.5.1
  - r>=3.4.1

# preprocessing.rules
  - trimmomatic>=0.36
  - r-ggplot2
  - r-tidyr
  - r-scales