channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
# general
  - snakemake>=5.4.4
  - python>=3.5.1
  - r>=3.4.1
  - pandas

# preprocessing.snk
  - trimmomatic>=0.36
  - r-ggplot2>=3.1.0
  - r-tidyverse
  - r-scales

# assembly.snk
  - spades>=3.13.0
  - trinity>=2.8.4
  - bowtie2>=2.3.2
  - bandage

# depletion.smk
  - ete3
